
####	ASSIGN:	3 - Manchester Baby
####	GROUP:	11
####			(Marc Giannandrea:	150014251)
####			(Ross Campbell:		150005746)
####			(Karl Theoren:		150008734)
####			(Daniel McGuinness:	150007957)
####	DATE:	21/11/16



main:
	g++ -o main *.cpp

clean:
	rm main
